//! `lx repo` — productize the prebuilt binary repository (Prebuilt-MPR
//! spirit): turn a directory of built `.deb`s into an apt-servable
//! repository with `Packages`, `Packages.gz`, `Release`, and a clearsigned
//! `InRelease` when a signing key is given. The `latest-debs` apt repo +
//! `lx install` against it is then a complete producer→distributor loop.

use anyhow::{bail, Context, Result};
use clap::Args;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Args)]
pub struct RepoArgs {
    /// Directory containing `.deb` files (also receives the index files).
    pub dir: PathBuf,

    /// Suite name recorded in `Release` (default: stable).
    #[arg(long, default_value = "stable")]
    pub suite: String,

    /// Path to an ASCII-armored secret key for clearsigning `InRelease`.
    /// Passphrase via $LX_SIGN_PASSPHRASE / $NFPM_PASSPHRASE. Without a
    /// key, only the unsigned `Release` is written.
    #[arg(long, value_name = "KEY_FILE")]
    pub sign_key: Option<PathBuf>,

    /// Signing key id / fingerprint (gpg --local-user).
    #[arg(long, value_name = "KEY_ID")]
    pub sign_key_id: Option<String>,
}

pub fn run(args: RepoArgs) -> Result<()> {
    if !args.dir.is_dir() {
        bail!("'{}' is not a directory", args.dir.display());
    }
    let mut debs: Vec<PathBuf> = std::fs::read_dir(&args.dir)?
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().map(|e| e == "deb").unwrap_or(false))
        .collect();
    debs.sort();
    if debs.is_empty() {
        bail!("no .deb files in '{}'", args.dir.display());
    }

    // One Packages stanza per .deb (Filename relative to the repo root).
    let mut stanzas = Vec::new();
    let mut archs = BTreeMap::new();
    for deb in &debs {
        let ctrl = read_control(deb)?;
        let name = deb.file_name().unwrap().to_string_lossy().to_string();
        let get = |k: &str| ctrl.get(k).cloned().unwrap_or_default();
        archs.insert(get("Architecture"), true);
        let size = std::fs::metadata(deb)?.len();
        let sha256 = lx_lib::checksum::sha256_file(deb)?;
        let stanza = format!(
            "Package: {}\nVersion: {}\nArchitecture: {}\nMaintainer: {}\nDepends: {}\nDescription: {}\nFilename: {}\nSize: {}\nSHA256: {}\n",
            get("Package"),
            get("Version"),
            get("Architecture"),
            get("Maintainer"),
            get("Depends"),
            get("Description"),
            name,
            size,
            sha256,
        );
        stanzas.push(stanza.trim_end_matches('\n').to_string());
    }
    let packages = stanzas.join("\n\n") + "\n";
    std::fs::write(args.dir.join("Packages"), &packages)?;
    let gz = lx_lib::debarchive::deterministic_gzip_bytes(packages.as_bytes(), 0, 9)?;
    std::fs::write(args.dir.join("Packages.gz"), &gz)?;

    // Release with hashes over both index files.
    let date = jiff::Timestamp::now()
        .strftime("%a, %d %b %Y %H:%M:%S UTC")
        .to_string();
    let mut arch_list: Vec<String> = archs.keys().cloned().collect();
    arch_list.sort();
    let mut release = format!(
        "Origin: latest-debs\nLabel: latest-debs\nSuite: {}\nCodename: {}\nDate: {}\nArchitectures: {}\nComponents: main\nDescription: latest-debs prebuilt repository (generated by lx repo)\n",
        args.suite,
        args.suite,
        date,
        arch_list.join(" ")
    );
    for index in ["Packages", "Packages.gz"] {
        let bytes = std::fs::read(args.dir.join(index))?;
        release.push_str(&index_hashes(index, &bytes));
    }
    std::fs::write(args.dir.join("Release"), &release)?;
    println!(
        "wrote Packages, Packages.gz, Release ({} packages)",
        debs.len()
    );

    if let Some(key) = &args.sign_key {
        let req = lx_lib::sign::SignRequest {
            key_file: key,
            key_id: args.sign_key_id.as_deref().unwrap_or_default(),
            passphrase: None,
        };
        let signed = lx_lib::sign::clearsign(release.as_bytes(), &req)?;
        std::fs::write(args.dir.join("InRelease"), &signed)?;
        println!("wrote InRelease (clearsigned)");
    } else {
        println!("no --sign-key: skipping InRelease (unsigned Release only)");
    }
    Ok(())
}

fn index_hashes(name: &str, bytes: &[u8]) -> String {
    use sha2::Digest;
    let md5 = format!("{:x}", md5::compute(bytes));
    let mut h1 = sha1::Sha1::new();
    h1.update(bytes);
    let sha1hex = hex::encode(h1.finalize());
    let mut h2 = sha2::Sha256::new();
    h2.update(bytes);
    let sha256hex = hex::encode(h2.finalize());
    format!(
        "MD5Sum:\n {md5} {} {name}\nSHA1:\n {sha1hex} {} {name}\nSHA256:\n {sha256hex} {} {name}\n",
        bytes.len(),
        bytes.len(),
        bytes.len()
    )
}

/// Read the `control` file out of a `.deb`'s control.tar.* member.
pub fn read_control(deb: &Path) -> Result<BTreeMap<String, String>> {
    let file = std::fs::File::open(deb).with_context(|| format!("opening '{}'", deb.display()))?;
    let mut archive = ar::Archive::new(file);
    while let Some(entry) = archive.next_entry() {
        let mut entry = entry?;
        let name = String::from_utf8_lossy(entry.header().identifier()).to_string();
        if !name.starts_with("control.tar") {
            continue;
        }
        let mut data = Vec::new();
        std::io::copy(&mut entry, &mut data)?;
        let text: Vec<u8> = if name.ends_with(".gz") {
            let mut gz = flate2::read::GzDecoder::new(data.as_slice());
            let mut out = Vec::new();
            std::io::copy(&mut gz, &mut out)?;
            out
        } else if name.ends_with(".xz") {
            let mut out = Vec::new();
            let mut dec = lzma_rust2::XzReader::new(data.as_slice(), true);
            std::io::copy(&mut dec, &mut out)?;
            out
        } else if name.ends_with(".zst") || name.ends_with(".zstd") {
            zstd::bulk::decompress(&data, 16 * 1024 * 1024)
                .context("zstd decompress control.tar")?
        } else {
            data
        };
        let mut ar = tar::Archive::new(text.as_slice());
        for member in ar.entries()? {
            let mut member = member?;
            let path = member.path()?.to_string_lossy().to_string();
            if path.ends_with("control") && member.header().entry_type().is_file() {
                let mut s = String::new();
                std::io::Read::read_to_string(&mut member, &mut s)?;
                return Ok(parse_control(&s));
            }
        }
        bail!(
            "control.tar member has no control file in '{}'",
            deb.display()
        );
    }
    bail!("'{}' has no control.tar.* member", deb.display())
}

/// Parse RFC-2822-style control fields (with continuation lines).
fn parse_control(text: &str) -> BTreeMap<String, String> {
    let mut map = BTreeMap::new();
    let mut key = String::new();
    for line in text.lines() {
        if line.starts_with([' ', '\t']) {
            if !key.is_empty() {
                map.entry(key.clone()).and_modify(|v: &mut String| {
                    v.push('\n');
                    v.push_str(line.trim());
                });
            }
        } else if let Some((k, v)) = line.split_once(':') {
            key = k.trim().to_string();
            map.insert(key.clone(), v.trim().to_string());
        }
    }
    map
}
