// SPDX-License-Identifier: GPL-3.0-or-later

//! Shell installer script generation.
//!
//! Generates a self-installing shell script (like cargo-dist) that downloads
//! and installs the appropriate package for the user's distro and architecture.

use anyhow::{Context, Result};
use std::path::{Path, PathBuf};

/// Generate a shell installer script for the built packages in `dir`.
pub fn generate_shell_installer(dir: &Path, package_name: &str, version: &str) -> Result<PathBuf> {
    // Build the script using raw strings to avoid Rust format! conflicts
    // with shell ${VAR} syntax.
    let mut script = String::new();
    script.push_str("#!/bin/sh\n");
    script.push_str(&format!("# {} v{} installer\n", package_name, version));
    script.push_str("# Generated by lx — install with: curl -sSL <url> | sh\n");
    script.push_str("set -e\n\n");
    script.push_str(&format!("NAME=\"{}\"\n", package_name));
    script.push_str(&format!("VERSION=\"{}\"\n", version));
    script.push_str("PREFIX=\"${PREFIX:-/usr/local}\"\n\n");

    script.push_str("# Detect architecture\n");
    script.push_str("arch=\"$(uname -m)\"\n");
    script.push_str("case \"$arch\" in\n");
    script.push_str(
        "    x86_64|amd64)  DEB_ARCH=\"amd64\"; RPM_ARCH=\"x86_64\"; ARCH_ARCH=\"x86_64\" ;;\n",
    );
    script.push_str(
        "    aarch64|arm64) DEB_ARCH=\"arm64\"; RPM_ARCH=\"aarch64\"; ARCH_ARCH=\"aarch64\" ;;\n",
    );
    script.push_str(
        "    armv7l|armhf)  DEB_ARCH=\"armhf\"; RPM_ARCH=\"armv7hl\"; ARCH_ARCH=\"armv7l\" ;;\n",
    );
    script.push_str(
        "    riscv64)       DEB_ARCH=\"riscv64\"; RPM_ARCH=\"riscv64\"; ARCH_ARCH=\"riscv64\" ;;\n",
    );
    script.push_str("    *) echo \"ERROR: unsupported architecture: $arch\"; exit 1 ;;\n");
    script.push_str("esac\n\n");

    script.push_str("# Detect OS and distribution\n");
    script.push_str("OS=\"$(uname -s | tr '[:upper:]' '[:lower:]')\"\n");
    script.push_str("if [ \"$OS\" = \"darwin\" ]; then\n");
    script.push_str("    echo \"macOS detected — downloading tar.gz archive\"\n");
    script.push_str("    EXT=\"tar.gz\"\n");
    script.push_str("    PKG_PATTERN=\"${NAME}_${VERSION}_darwin_${ARCH_ARCH}.tar.gz\"\n");
    script.push_str("elif [ \"$OS\" = \"linux\" ]; then\n");
    script.push_str("    if [ -f /etc/os-release ]; then\n");
    script.push_str("        . /etc/os-release\n");
    script.push_str("        case \"$ID\" in\n");
    script.push_str("            debian|ubuntu|linuxmint|pop) EXT=\"deb\"; PKG_PATTERN=\"${NAME}_${VERSION}-1+${DEB_ARCH}.deb\" ;;\n");
    script.push_str("            fedora)                        EXT=\"rpm\"; PKG_PATTERN=\"${NAME}_${VERSION}-1.${RPM_ARCH}.rpm\" ;;\n");
    script.push_str("            arch|manjaro)                  EXT=\"pkg.tar.zst\"; PKG_PATTERN=\"${NAME}_${VERSION}-1-${ARCH_ARCH}.pkg.tar.zst\" ;;\n");
    script.push_str("            *)                             EXT=\"tar.gz\"; PKG_PATTERN=\"${NAME}_${VERSION}_linux_${ARCH_ARCH}.tar.gz\" ;;\n");
    script.push_str("        esac\n");
    script.push_str("    else\n");
    script.push_str("        EXT=\"tar.gz\"\n");
    script.push_str("        PKG_PATTERN=\"${NAME}_${VERSION}_linux_${ARCH_ARCH}.tar.gz\"\n");
    script.push_str("    fi\n");
    script.push_str("else\n");
    script.push_str("    echo \"ERROR: unsupported OS: $OS\"\n");
    script.push_str("    exit 1\n");
    script.push_str("fi\n\n");

    script.push_str("# Base URL — override with RELEASE_URL env\n");
    script.push_str(
        "BASE_URL=\"${RELEASE_URL:-https://github.com/USER/REPO/releases/download/v$VERSION}\"\n",
    );
    script.push_str("PKG_URL=\"$BASE_URL/$PKG_PATTERN\"\n");
    script.push_str("SHA_URL=\"$BASE_URL/$PKG_PATTERN.sha256\"\n\n");

    script.push_str("echo \"Downloading $PKG_PATTERN...\"\n\n");

    script.push_str("# Create temp dir\n");
    script.push_str("TMPDIR=\"$(mktemp -d)\"\n");
    script.push_str("trap 'rm -rf \"$TMPDIR\"' EXIT\n\n");

    script.push_str("# Download package\n");
    script.push_str("if command -v curl >/dev/null 2>&1; then\n");
    script.push_str("    curl -fsSL \"$PKG_URL\" -o \"$TMPDIR/$PKG_PATTERN\"\n");
    script.push_str("elif command -v wget >/dev/null 2>&1; then\n");
    script.push_str("    wget -q \"$PKG_URL\" -O \"$TMPDIR/$PKG_PATTERN\"\n");
    script.push_str("else\n");
    script.push_str("    echo \"ERROR: need curl or wget\"\n");
    script.push_str("    exit 1\n");
    script.push_str("fi\n\n");

    script.push_str("# Verify checksum if available\n");
    script.push_str("if [ \"$EXT\" != \"tar.gz\" ]; then\n");
    script.push_str(
        "    if curl -fsSL \"$SHA_URL\" -o \"$TMPDIR/$PKG_PATTERN.sha256\" 2>/dev/null; then\n",
    );
    script.push_str("        echo \"Verifying checksum...\"\n");
    script.push_str("        EXPECTED=\"$(cat \"$TMPDIR/$PKG_PATTERN.sha256\")\"\n");
    script.push_str("        if command -v sha256sum >/dev/null 2>&1; then\n");
    script
        .push_str("            ACTUAL=\"$(sha256sum \"$TMPDIR/$PKG_PATTERN\" | cut -d' ' -f1)\"\n");
    script.push_str("        elif command -v shasum >/dev/null 2>&1; then\n");
    script.push_str(
        "            ACTUAL=\"$(shasum -a 256 \"$TMPDIR/$PKG_PATTERN\" | cut -d' ' -f1)\"\n",
    );
    script.push_str("        else\n");
    script.push_str("            echo \"WARNING: cannot verify checksum (no sha256sum/shasum)\"\n");
    script.push_str("            ACTUAL=\"$EXPECTED\"\n");
    script.push_str("        fi\n");
    script.push_str("        if [ \"$EXPECTED\" != \"$ACTUAL\" ]; then\n");
    script.push_str("            echo \"ERROR: checksum mismatch\"\n");
    script.push_str("            exit 1\n");
    script.push_str("        fi\n");
    script.push_str("        echo \"  checksum verified\"\n");
    script.push_str("    fi\n");
    script.push_str("fi\n\n");

    script.push_str("# Install\n");
    script.push_str("echo \"Installing...\"\n");
    script.push_str("case \"$EXT\" in\n");
    script.push_str("    deb)\n");
    script.push_str("        if command -v sudo >/dev/null 2>&1; then\n");
    script.push_str(
        "            sudo dpkg -i \"$TMPDIR/$PKG_PATTERN\" || sudo apt-get install -f -y\n",
    );
    script.push_str("        else\n");
    script.push_str("            dpkg -i \"$TMPDIR/$PKG_PATTERN\" || apt-get install -f -y\n");
    script.push_str("        fi\n");
    script.push_str("        ;;\n");
    script.push_str("    rpm)\n");
    script.push_str("        if command -v sudo >/dev/null 2>&1; then\n");
    script.push_str("            sudo rpm -i \"$TMPDIR/$PKG_PATTERN\" || sudo dnf install -y \"$TMPDIR/$PKG_PATTERN\"\n");
    script.push_str("        else\n");
    script.push_str(
        "            rpm -i \"$TMPDIR/$PKG_PATTERN\" || dnf install -y \"$TMPDIR/$PKG_PATTERN\"\n",
    );
    script.push_str("        fi\n");
    script.push_str("        ;;\n");
    script.push_str("    pkg.tar.zst)\n");
    script.push_str("        if command -v sudo >/dev/null 2>&1; then\n");
    script.push_str("            sudo pacman -U --noconfirm \"$TMPDIR/$PKG_PATTERN\"\n");
    script.push_str("        else\n");
    script.push_str("            pacman -U --noconfirm \"$TMPDIR/$PKG_PATTERN\"\n");
    script.push_str("        fi\n");
    script.push_str("        ;;\n");
    script.push_str("    tar.gz)\n");
    script.push_str("        tar xzf \"$TMPDIR/$PKG_PATTERN\" -C \"$PREFIX\"\n");
    script.push_str("        echo \"Extracted to $PREFIX\"\n");
    script.push_str("        ;;\n");
    script.push_str("esac\n\n");

    script.push_str(&format!(
        "echo \"✓ {} v{} installed successfully\"\n",
        package_name, version
    ));

    let script_path = dir.join(format!("{package_name}-install.sh"));
    std::fs::write(&script_path, script)
        .with_context(|| format!("writing installer script '{}'", script_path.display()))?;

    // Make executable.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(&script_path)
            .context("reading installer metadata")?
            .permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(&script_path, perms).context("setting installer permissions")?;
    }

    println!("  ✓ generated shell installer: {}", script_path.display());
    Ok(script_path)
}
